services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: tododb
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123

volumes:
  mysql_data: